### ISSUE TITLE
Search by name

### ISSUE THREAD

**Issue by Nama** [Trsnaqe/protondb-community-api#2]
Hi,

thank you for this!

It would be nice to search for the game by the name.
I had a short look into it and it seems steam (also nobody else) are providing such interface D:
Ppl seem to get the big json from steam and search throu it. It's unideal, but seems to be the only way.

Would be possible to implement that feature?

Thanks

**Comment by Trsnaqe** [comment]
Hello,

I'm glad to hear that you found this useful! I can implement a text search on the database side using indexes. This would be significantly better in terms of search speed and efficiency. I'll try to work on this when I have some free time.

Thank you for the feedback!

**Comment by Trsnaqe** [comment]
Hey,

I’ve just updated the API! Please take a look at the [latest release](https://github.com/Trsnaqe/protondb-community-api/releases/tag/V2) and check out the new v2 endpoints. I hope this updates meet your needs. If you run into any bugs or have any feedback, please don't hesitate to let me know! 

Thanks!
